--Below is to add to a MySQL database if you want to create the table to "secova25/studentrecords" in PostgreSQL due:

CREATE TABLE IF NOT EXISTS StudentRecord(
	FNAME VARCHAR(50),
	MNAME VARCHAR(50),
	LNAME VARCHAR(50),
	USERNAME VARCHAR(50) PRIMARY KEY,
    CLASSNAME VARCHAR(50),
	CREDITTYPE VARCHAR(50),
	CREDITVALUE int
);
CREATE TABLE IF NOT EXISTS UserProfile(
	FNAME VARCHAR(50),
	MNAME VARCHAR(50),
	LNAME VARCHAR(50),
	USERNAME VARCHAR(50) PRIMARY KEY,
    PASSWORD1 VARCHAR(50)
);
